# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-16 09:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('street_address', models.CharField(blank=True, max_length=500)),
                ('postal_code', models.CharField(blank=True, max_length=15)),
                ('city', models.CharField(default='Villeurbanne', max_length=100)),
                ('country', django_countries.fields.CountryField(default='FR', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=200)),
                ('amount', models.IntegerField()),
                ('status', models.CharField(choices=[('ST', 'Démarré'), ('DR', 'Brouillon'), ('IP', 'En cours'), ('FA', 'Échoué'), ('SU', 'Réussi')], max_length=2)),
                ('method', models.CharField(choices=[('TEST', 'Test'), ('MERC', 'Mercanet'), ('STRP', 'Stripe'), ('PP', 'Paypal'), ('MCB', 'Carte bancaire'), ('MCHQ', 'Chèque'), ('MESP', 'Espèces'), ('MVIR', 'Virement')], max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='applications.Application')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='trezo.Client')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(choices=[('ST', 'Démarré'), ('DR', 'Brouillon'), ('IP', 'En cours'), ('FA', 'Échoué'), ('SU', 'Réussi')], max_length=2)),
                ('to_status', models.CharField(choices=[('ST', 'Démarré'), ('DR', 'Brouillon'), ('IP', 'En cours'), ('FA', 'Échoué'), ('SU', 'Réussi')], max_length=2)),
                ('signature', models.TextField()),
                ('method_data', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='trezo.Payment')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_app_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('taxes', models.FloatField(null=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='applications.Application')),
            ],
        ),
        migrations.AddField(
            model_name='payment',
            name='products',
            field=models.ManyToManyField(related_name='payments', to='trezo.Product'),
        ),
    ]
